### ISSUE TITLE
fail to build and install debian package in ubuntu 20.04

### ISSUE THREAD

**Issue by shenfang2019** [tttech-industrial-buchsbaum/acrn-hypervisor#4]
**Describe the bug**
fail to build and install debian package in ubuntu 20.04.

**Platform**
adl-s with ubuntu 20.04

**Codebase**
acrn-hypervisor commit id:3d8fa8094941077f8ee15a3def0f5e79a201a173
with the following debian patches:
0001-Update-gitignore-to-ignore-Eclipse-project-config.patch 0006-hv-Fixup-serial.conf-permissions.patch
0002-board-inspector-Fix-sys.path-for-all-internal-module.patch 0007-debian-Handle-etc-serial.conf.patch
0003-dm-Use-libdrm-library-for-drm-access.patch 0008-dm-Remove-dependency-on-libuuid.patch
0004-Adding-initial-native-Debian-packaging-for-ACRN.patch 0009-debian-Remove-build-dependency-on-uuid-dev.patch
0005-debian-Add-docker-build-helpers.patch 0010-Update-d-changelog.patch

**Scenario**
Building ACRN 3.0 for boards: adl-s-crb, cfl-k700-i7, nuc11tnbi5, tgl-vecow-spc-7100-Corei7, whl-ipc-i5
The scenarios used are:
adl-s-crb: partitioned, shared, hybrid, hybrid_rt
cfl-k700-i7: partitioned, shared, hybrid, hybrid_rt
nuc11tnbi5: partitioned, shared, hybrid
tgl-vecow-spc-7100-Corei7: partitioned, shared, hybrid
whl-ipc-i5: partitioned, shared, hybrid, hybrid_rt

**To Reproduce**
1. git clone acrn-hypervisor with 3d8fa8094941077f8ee15a3def0f5e79a201a173
2. add debian 10 patches
3. cd acrn-hypervisor
4. gbp buildpackage --git-ignore-new
5. See error:
gbp:info: Performing the build
 dpkg-buildpackage -us -uc -ui -i -I
dpkg-buildpackage: info: source package acrn-hypervisor
dpkg-buildpackage: info: source version 3.0~2.gbp6418b0
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Helmut Buchsbaum <helmut.buchsbaum@opensource.tttech-industrial.com>
 dpkg-source -i -I --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: acpica-tools (>= 20200326) python3-xmlschema
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I failed
gbp:error: 'debuild -i -I' failed: it exited with 29

1. copy debian package built from 21.04 ubuntu on TGL to 20.04 ubuntu on ADL-S
2. dpkg -i *.deb
3. 
The following packages have unmet dependencies:
 acrn-devicemodel : Depends: libc6 (>= 2.33) but 2.31-0ubuntu9.7 is to be installed
                    Depends: libsdl2-2.0-0 (>= 2.0.12) but 2.0.10+dfsg1-3 is to be installed
                    Depends: acpica-tools (>= 20200326) but 20190509-1 is to be installed
 acrn-lifemngr : Depends: libc6 (>= 2.33) but 2.31-0ubuntu9.7 is to be installed
 acrn-tools : Depends: libc6 (>= 2.33) but 2.31-0ubuntu9.7 is to be installed
 acrnd : Depends: libc6 (>= 2.33) but 2.31-0ubuntu9.7 is to be installed
 grub-acrn : Depends: grub-efi-amd64
 python3-acrn-board-inspector : Depends: python3-xmlschema but it is not installable
[install-fail-adl-s.txt](https://github.com/tttech-industrial-buchsbaum/acrn-hypervisor/files/8572078/install-fail-adl-s.txt)

**Expected behavior**
no error
but now it's complex to install some dependent lib.

**Comment by tttech-industrial-buchsbaum** [comment]
Just follow the procedure given in https://github.com/projectacrn/acrn-hypervisor/pull/7398, but build for Ubuntu Focal Fossa:
```
user@host:~/work/acrn-hypervisor$ DISTRO=focal VENDOR=ubuntu debian/docker/acrn-docker-build.sh --git-ignore-branch
```
This will provide any missing packages and the correct dependencies. Do not forget to use the provided local APT repository on the target system for easy installation!

ATTENTION: Ubuntu & Debian **ALWAYS** use an initrd together with their kernel images. This is required to integrate with their system properly. As a consequence youe need a respective scenario providing a `Linux_initrd`, which is referred to in the grub-acrn package to build prober grub configurations at install time. This is why I provided shared+initrd scenarios for nuc7i7dnh and kontron-COMe-mAL10, which are the platform I have tested with.
BTW, on kontron-COMe-mAL10 I also testes Ubuntu 20.04 successfully.

P.S.: Please use at least commit b7f50ef980edaf6c7d51b72984d889edf0ba006e on master to apply the changes.

**Comment by tttech-industrial-buchsbaum** [comment]
Package install and use has been proven to work with kontron-COMe-mAL10/shared-initrd on a Ubuntu 20.04 server distribution as described in https://github.com/projectacrn/acrn-hypervisor/pull/7398.
